/* Populate tabla clientes */
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Josue', 'Ponte', 'jodpontr@gmail.com', '2023-02-14' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Daniel',  'Rojas', 'correo@gmail.com', '2023-02-13');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Fiorella', 'Talavera', 'correo1@gmail.com', '2023-02-12' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Mirella', 'Berrocal', 'correo2@gmail.com', '2023-02-11' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Noé', 'Salinas', 'correo3@gmail.com', '2023-02-10');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'Patricio', 'correo4@gmail.com', '2023-02-09');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Raquel', 'Tena', 'correo5@gmail.com', '2023-02-08' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hubert', 'Calla', 'correo6@gmail.com', '2023-02-07' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Percy', 'Rojas', 'correo7@gmail.com', '2023-02-06' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Saith', 'Calla', 'correo9@gmail.com', '2023-02-05' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Karin', 'Rojas', 'correo10@gmail.com', '2023-02-04' );
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gerson', 'Regalado', 'correo11@gmail.com', '2023-02-03' );

/* tabla producto */
INSERT INTO products (nombre, precio, create_at) VALUES ('Product 1', 2999, NOW());
INSERT INTO products (nombre, precio, create_at) VALUES ('Product 2', 3999, NOW());
INSERT INTO products (nombre, precio, create_at) VALUES ('Product 3', 4999, NOW());
INSERT INTO products (nombre, precio, create_at) VALUES ('Product 4', 5999, NOW());
INSERT INTO products (nombre, precio, create_at) VALUES ('Product 5', 6999, NOW());
INSERT INTO products (nombre, precio, create_at) VALUES ('Product 6', 7999, NOW());
INSERT INTO products (nombre, precio, create_at) VALUES ('Product 7', 8999, NOW());

/* tabla orders */
INSERT INTO orders (descripcion, observacion, cliente_id, create_at) VALUES('Orden de Productos 1', null, 1, NOW());
INSERT INTO order_details (cantidad, order_id, product_id) VALUES(1, 1, 1);
INSERT INTO order_details (cantidad, order_id, product_id) VALUES(2, 1, 4);
INSERT INTO order_details (cantidad, order_id, product_id) VALUES(1, 1, 5);
INSERT INTO order_details (cantidad, order_id, product_id) VALUES(1, 1, 7);

INSERT INTO orders (descripcion, observacion, cliente_id, create_at) VALUES('Orden de Productos 2', 'Alguna Nota Importante!', 1, NOW());
INSERT INTO order_details (cantidad, order_id, product_id) VALUES(3, 2, 6);
INSERT INTO order_details (cantidad, order_id, product_id) VALUES(2, 2, 4);